### ISSUE TITLE
ERRER

### ISSUE THREAD

**Issue by 79121262** [yakagami/zoom_view#9]
RenderBox.size accessed beyond the scope of resize, layout, or permitted parent access. RenderBox can always access its own size, otherwise, the only object that is allowed to read RenderBox.size is its parent, if they have said they will. It you hit this assert trying to access a child's size, pass "parentUsesSize: true" to that child's layout() in RenderStack.performLayout.
'package:flutter/src/rendering/box.dart':
Failed assertion: line 2178 pos 16: 'sizeAccessAllowed'

**Comment by yakagami** [comment]
Can you post your code? Would be best if you could make an example that is simple. But either is fine.

**Comment by 79121262** [comment]
Please ignore this issue, there is a problem with my code structure
